# Generated by Django 5.2.4 on 2025-09-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pecas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peca',
            name='fornecedor',
            field=models.CharField(max_length=100, verbose_name='Fornecedor'),
        ),
        migrations.AlterModelOptions(
            name='peca',
            options={'verbose_name': 'Peça', 'verbose_name_plural': 'Peças'},
        ),
        migrations.AddField(
            model_name='peca',
            name='endereco_bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='peca',
            name='endereco_cep',
            field=models.CharField(blank=True, max_length=10, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='peca',
            name='endereco_cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='peca',
            name='endereco_complemento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='peca',
            name='endereco_estado',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='peca',
            name='endereco_numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='peca',
            name='endereco_rua',
            field=models.CharField(blank=True, max_length=200, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='peca',
            name='telefone_fornecedor',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone do Fornecedor'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição da Peça'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='marca',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marca da Peça'),
        ),
        migrations.DeleteModel(
            name='Fornecedor',
        ),
    ]
