# Generated by Django 5.2.4 on 2025-09-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pecas', '0002_alter_peca_fornecedor_alter_peca_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peca',
            options={'ordering': ['-data_cadastro'], 'verbose_name': 'Peça', 'verbose_name_plural': 'Peças'},
        ),
        migrations.AddField(
            model_name='peca',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data de Atualização'),
        ),
        migrations.AddField(
            model_name='peca',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='marca',
            field=models.CharField(max_length=100, verbose_name='Marca da Peça'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='telefone_fornecedor',
            field=models.CharField(max_length=20, verbose_name='Telefone do Fornecedor'),
        ),
    ]
